CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FNAME TEXT,
    LNAME TEXT,
    EMAIL TEXT,
    AGE INTEGER
);

CREATE TABLE IF NOT EXISTS QUIZ (
    CODE TEXT PRIMARY KEY,
    TITLE TEXT,
    START_TIME DATETIME,
    DURATION FLOAT,
    NO_QUESTIONS INTEGER
);

CREATE TABLE IF NOT EXISTS RESULT (
    RESULT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SCORE INTEGER,
    USER_ID INTEGER,
    QUIZ_CODE TEXT,
    TIME_TAKEN FLOAT,
    SUBMITTED_AT DATETIME,
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)  ON DELETE CASCADE,
    FOREIGN KEY(QUIZ_CODE) REFERENCES QUIZ(CODE)  ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUESTION (
    QUESTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    QUESTION_TEXT TEXT,
    DIFFICULTY INTEGER,
    QUIZ_CODE TEXT,
    FOREIGN KEY(QUIZ_CODE) REFERENCES QUIZ(CODE) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ANSWER (
    ANSWER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ANSWER_TEXT TEXT,
    IS_CORRECT BOOLEAN,
    QUESTION_ID INTEGER,
    FOREIGN KEY(QUESTION_ID) REFERENCES QUESTION(QUESTION_ID) ON DELETE CASCADE
);